[package]
name = "futures_tag_locks"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
futures-locks = "0.3"
version_tag = { git = "https://github.com/danylaporte/version_tag.git" }

[dev-dependencies]
tokio = "0.1"
