(function() {var implementors = {};
implementors["futures_tag_locks"] = [{text:"impl&lt;F, FUT&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"futures_tag_locks/struct.RwLockReadInitFut.html\" title=\"struct futures_tag_locks::RwLockReadInitFut\">RwLockReadInitFut</a>&lt;F, FUT&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;F: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/function/trait.Fn.html\" title=\"trait core::ops::function::Fn\">Fn</a>() -&gt; FUT,<br>&nbsp;&nbsp;&nbsp;&nbsp;FUT: <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.IntoFuture.html\" title=\"trait futures::future::IntoFuture\">IntoFuture</a>,&nbsp;</span>",synthetic:false,types:["futures_tag_locks::rw_lock::RwLockReadInitFut"]},{text:"impl&lt;T:&nbsp;?<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> + <a class=\"trait\" href=\"futures_tag_locks/trait.SetTag.html\" title=\"trait futures_tag_locks::SetTag\">SetTag</a>&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"futures_tag_locks/struct.RwLockWriteFut.html\" title=\"struct futures_tag_locks::RwLockWriteFut\">RwLockWriteFut</a>&lt;T&gt;",synthetic:false,types:["futures_tag_locks::rw_lock::RwLockWriteFut"]},{text:"impl&lt;F, FUT&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"futures_tag_locks/struct.RwLockWriteInitFut.html\" title=\"struct futures_tag_locks::RwLockWriteInitFut\">RwLockWriteInitFut</a>&lt;F, FUT&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;F: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/function/trait.Fn.html\" title=\"trait core::ops::function::Fn\">Fn</a>() -&gt; FUT,<br>&nbsp;&nbsp;&nbsp;&nbsp;FUT: <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.IntoFuture.html\" title=\"trait futures::future::IntoFuture\">IntoFuture</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;FUT::<a class=\"type\" href=\"https://docs.rs/futures/0.1/futures/future/trait.IntoFuture.html#associatedtype.Item\" title=\"type futures::future::IntoFuture::Item\">Item</a>: <a class=\"trait\" href=\"futures_tag_locks/trait.SetTag.html\" title=\"trait futures_tag_locks::SetTag\">SetTag</a>,&nbsp;</span>",synthetic:false,types:["futures_tag_locks::rw_lock::RwLockWriteInitFut"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
