(function() {var implementors = {};
implementors["futures_tag_locks"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"futures_tag_locks/struct.RwLockReadInitGuard.html\" title=\"struct futures_tag_locks::RwLockReadInitGuard\">RwLockReadInitGuard</a>&lt;T&gt;",synthetic:false,types:["futures_tag_locks::rw_lock::RwLockReadInitGuard"]},{text:"impl&lt;T:&nbsp;?<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> + <a class=\"trait\" href=\"futures_tag_locks/trait.SetTag.html\" title=\"trait futures_tag_locks::SetTag\">SetTag</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"futures_tag_locks/struct.RwLockWriteGuard.html\" title=\"struct futures_tag_locks::RwLockWriteGuard\">RwLockWriteGuard</a>&lt;T&gt;",synthetic:false,types:["futures_tag_locks::rw_lock::RwLockWriteGuard"]},{text:"impl&lt;T:&nbsp;?<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"futures_tag_locks/struct.Tagged.html\" title=\"struct futures_tag_locks::Tagged\">Tagged</a>&lt;T&gt;",synthetic:false,types:["futures_tag_locks::tagged::Tagged"]},{text:"impl&lt;T:&nbsp;?<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"futures_tag_locks/struct.Untagged.html\" title=\"struct futures_tag_locks::Untagged\">Untagged</a>&lt;T&gt;",synthetic:false,types:["futures_tag_locks::untagged::Untagged"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
